apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-gitcall-docker-network-policy
  namespace: {{ .Release.Namespace | quote }}
  labels:
    release: {{ .Release.Name | quote }}
    app: {{ .Values.helm.app | quote }}
    tier: {{ .Values.helm.tier | quote }}
spec:
  selector: tier == 'docker_server'
  types:
    - Egress
    - Ingress
  ingress:
    # Prometheus
    - action: Allow
      protocol: TCP
      source:
        namespaceSelector: projectcalico.org/name == 'monitoring'
        selector: app == 'prometheus'
      destination:
        ports:
          - 9323
    # Gitcall
    - action: Allow
      protocol: TCP
      source:
        selector: tier == 'gitcall'
      destination:
        ports:
          # TLS
          - 2376
          # Plain
          - 2375
  egress:
    - action: Allow
